# Generated by Django 4.1.7 on 2023-03-26 11:50

import card_manager.custom_fields
import card_manager.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "exp_date",
                    card_manager.custom_fields.CustomDateGeneratedField(
                        max_length=10,
                        validators=[card_manager.validations.validate_exp_date],
                    ),
                ),
                (
                    "holder",
                    models.CharField(
                        max_length=50,
                        validators=[card_manager.validations.validate_holder],
                    ),
                ),
                (
                    "card_number",
                    card_manager.custom_fields.CustomEncryptedField(
                        max_length=255,
                        unique=True,
                        validators=[card_manager.validations.validate_card_number],
                    ),
                ),
                (
                    "cvv",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[card_manager.validations.validate_cvv],
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
